config/routes.rb
Rooomates::Application.routes.draw do
 resources :potentials
 resource :sessions
 resources :users 
 resources :profiles

 
 root "static_page#home"
 

end

app/models/user.rb
require "bcrypt"

class User < ActiveRecord::Base
 include BCrypt
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates_presence_of :name, 
        :age,
        :gender,
        :city,
        :state 
  validates_uniqueness_of :email
        
  # has_one :profile
  # has_many :potentials
  has_one :profile
  has_many :favorable_links, class_name: "Potential", foreign_key: :user_id, inverse_of: :user
  has_many :favorables, through: :favorable_links, class_name: "Profile", foreign_key: :favorable_id
  # This method associates the attribute ":avatar" with a file attachment
  has_attached_file :avatar, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }, :default_style => :display

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  acts_as_messageable


  def password
    @password
  end

  def password=(new_password)
    @password = new_password
    self.password_digest=BCrypt::Password.create(new_password)
  
  end
  

  def authenticate(test_password)
    if BCrypt::Password.new(self.password_digest) == test_password
      self
    else
      false
    end
  end

def forgot_password
  @user = User.find_by_email(params[:email])
  random_password = Array.new(10).map { (65 + rand(58)).chr }.join
  @user.password = random_password
  @user.save!
  Mailer.create_and_deliver_password_change(@user, random_password)
end


def favorable(opts={})
  # favorable_type
  type = opts[:type] ? opts[:type] : :topic
  type = type.to_s.capitalize
  # add favorable_id to condition if id is provided
  con = ["user_id = ? AND favorable_type = ?", self.id, type]
  
  # append favorable id to the query if an :id is passed as an option into the
  # function, and then append that id as a string to the "con" Array
  if opts[:id]
    con[0] += " AND favorable_id = ?"
    con << opts[:id].to_s
  end
 
  # Return all Favorite objects matching the above conditions
  favs = Favorite.all(:conditions => con)
  
  case opts[:delve]
  when nil, false, :false
    return favs
  when true, :true
    # get a list of all favorited object ids
    fav_ids = favs.collect{|f| f.favorable_id.to_s}

    if fav_ids.size > 0
      # turn the Capitalized favorable_type into an actual class Constant
      type_class = type.constantize

      # build a query that only selects
      query = []
      fav_ids.size.times do
        query << "id = ?"
      end
      type_conditions = [query.join(" AND ")] + fav_ids

      return type_class.all(:conditions => type_conditions)
    else
      return []
    end
  end       
end









end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :json

  def new
    @user = User.new
  end



  def create
    @user = User.new(user_params)
 

    if @user.save
      flash[:success] = "You have signed up successfully."
       @current_user = @user
       session[:user_id] = @user.id.to_s
       redirect_to users_path
    else
      flash[:error] = @user.errors
      redirect_to root_path
    end
  end

  def index
    @users = User.all
    respond_with current_user
    
  end


  def show
  end

  def edit
  end

  def update
  end

  def delete
  end

  protected

  def user_params
    params.require(:user).permit(:name, :age, :gender, :city, :state, :email, :password, :avatar)
  end
  
  
end

app/helpers/users_helper.rb
module UsersHelper

	
end

app/views/users/_forms.html.erb
	<div class="signupbox" id="about">
	

	</div>

<div class="signupbox" id="signupform">
	

<br><br>
	<%= form_for User.new do |f| %>


	<p>
	<%= f.text_field :email, :placeholder => "Email", class: "formuser" %>
	<%= f.password_field :password, :placeholder => "Password",  class: "formuser"%>
	<%= f.text_field :name, :placeholder => "Name", class: "formname" %>
	<%= f.text_field :age, :placeholder => "Age", class: "formuser"  %>
	<%= f.select :gender, options_for_select(%w[Male Female LGBT]), class: "formselect" %>
	<%= f.text_field :city, :placeholder => "City",class: "formuser"%>
	<%= f.text_field :state, :placeholder => "State", class: "formuser"%>

	</p>
	<%= f.label :avatar %>
  	<%= f.file_field :avatar %>
	
	<%= button_to('Create Account', users_path, :class => 'butt')  %>
	<% end %>
	

</div>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="userindex" x-ng-app="profile-app" x-ng-controller="ProfileCtrl" >
	<div class="homenavigation">
		<%= link_to "Sign Out", sessions_path, :method => :delete, class: "signoutlink" %>
		<div class="linksnav">
			<div class="linksnavtext"><u><%= link_to 'HOME', users_path %></u></div>
			<div class="linksnavtext"><u>SETTINGS</u></div>
			<div class="linksnavtext" id="settings"><%=link_to 'POTENTIALS', potentials_path %></div>
			<div class="linksnavtext" id="settings"><u>MESSAGES</u></div>
		</div>
	</div>


	<div class="small-6 large-2 columns" id="usersidebar">
		<div class="sidetitle">FILTERS:</div>
			<div class="usercat" ng-if="user.profile">
				<div class="looking"></div>
				<div class="lookingfor"></div>
				<div class="filterpic"></div>
			</div>
	</div>

	
	<div class="small-6 large-7 columns" id="profilefeed" >
			<div class="profiles" ng-model="profiles" ng-repeat="p in profiles" ng-if="user.profile"> 
				<div class="profpicindex">
					<img ng-src="{{p.user.avatar_url}}" />
				</div>
				<span class="username">{{p.user.name}}</span>	<br>
				<span class="profdetails">{{p.user.age}}</span>	<br>
				<span class="profdetails">{{p.user.city}}, {{p.user.state}}</span>
				<br><br><br>
				<h1 class="proftitle">CLEANLINESS:
					<span class="profattributes">{{p.cleanliness}}</span><br></h1>

				<h1 class="proftitle">NOISE TOLERANCE: 
					<span class="profattributes">{{p.noise_tolerance}}<br></span>	</h1>
				
				<h1 class="proftitle">VISITORS:
					<span class="profattributes">{{p.visitors}}<br>	</span></h1>

				<h1 class="proftitle">QUIET HOURS:
					<span class="profattributes">{{p.pets}}<br></span>	</h1>
		
				<h1 class="proftitle">PETS:
					<span class="profattributes">{{p.pets}}<br></span>	</h1>

				<h1 class="proftitle">SMOKING:
					<span class="profattributes">{{p.smoking}}<br>	</span></h1>

				<div class="addtopotential" ng-click="savePotential(p)" id="addtopotential">
				
				</div>
			</div>

			<div class= "profileform" ng-hide="user.profile">
					<h3>Hello, <%= current_user.name %>! <br><br>Tell us about yourself.</h3>
			
				<form name="profileForm" ng-submit="saveProfile();" class="form-group" >
				
				<label for=“cleanliness” class=“questions”></label>
					<h2 class="topic">  Cleanliness:</h1> <br>
						<input type="radio" ng-model="newProfile.cleanliness" name="cleanliness" value="5" id="answer">
					<h2 class="rating"> I want the house to be clean and organized all the time.</h2> <br>
						<input type="radio" ng-model="newProfile.cleanliness" name="cleanliness" value="4">
					<h2 class="rating">I want the general areas to be clean and organized most of the time.</h2><br>
						<input type="radio" ng-model="newProfile.cleanliness" name="cleanliness" value="3">
					<h2 class="rating"> I want the house to be generally neat and am willing to put up with a little mess.</h2><br>
						<input type="radio" ng-model="newProfile.cleanliness" name="cleanliness" value="2">
					<h2 class="rating"> It does not bother me if the house is disorganized just as long as it is clean.</h2><br>
						<input type="radio" ng-model="newProfile.cleanliness" name="cleanliness" value="1">
					<h2 class="rating"> It does not bother me if the house is generally cluttered and disorganized.</h2><br>
				<label for="noise_tolerance" class=“questions”></label>
					<h1 class="topic">  Noise tolerance:</h1> <br/>
						<input type="radio" ng-model="newProfile.noise_tolerance" name="noise_tolerance" value="5" id="answer">
					<h2 class="rating"> I can't stand noise and would prefer to have it quite around the house all the time. </h2> <br/>
						<input type="radio" ng-model="newProfile.noise_tolerance" name="noise_tolerance" value="4">
					<h2 class="rating"> I can't stand loud noises but don't mind chatter.</h2><br/>
						<input type="radio" ng-model="newProfile.noise_tolerance" name="noise_tolerance" value="3">
					<h2 class="rating"> I don't mind noise as long I am not sleeping/resting.</h2><br/>
						<input type="radio" ng-model="newProfile.noise_tolerance" name="noise_tolerance" value="2">
					<h2 class="rating">I don't mind it noise from time to time.</h2><br>
						<input type="radio" ng-model="newProfile.noise_tolerance" name="noise_tolerance" value="1">
						<h2 class="rating"> I don't mind noise at all. </h2><br/>

				<label for="visitors" class=“questions”></label>
					<h1 class="topic">  Visitors:</h1><br/><br/>
						How do you feel about about your roommate having visitors over?<br><br>
						<input type="radio" ng-model="newProfile.visitors" name="visitors" value="5" id="answer">
					<h2 class="rating"> I don't mind having visitors over everyday. </h2> <br/>
						<input type="radio" ng-model="newProfile.visitors" name="visitors" value="4">
					<h2 class="rating"> I don't mind having visitors 3-5 times a week.</h2><br/>
						<input type="radio" ng-model="newProfile.visitors" name="visitors" value="3">
					<h2 class="rating"> I don't mind having visitors as long as you let me know in advance.</h2><br/>
						<input type="radio" ng-model="newProfile.visitors" name="visitors" value="2">
					<h2 class="rating"> I would prefer having visitors only on the weekends.</h2><br>
						<input type="radio" ng-model="newProfile.visitors" name="visitors" value="1">
					<h2 class="rating"> I don't like strangers in my home. </h2><br><br/>

				<label for="sleeping_hours"  class="questions">
					<h1 class="topic">   Sleeping Hours:</h1><br></label><br>
						I sleep/prefer peace and quiet at around this time:&nbsp;
					<input ng-model="newProfile.sleeping_hours" name="sleeping_hours" class="form-control"><br><br>
						<br><br>
								
				<label for="cooks"  class="questions">
					<h1 class="topic"> How often do you cook at home?</h1><br/> </label>
						<input type="radio" ng-model="newProfile.cooks" name="cooks" value="3">
					<h2 class="rating">I cook at home all the time.</h2><br/>
						<input type="radio" ng-model="newProfile.cooks" name="cooks" value="2">
					<h2 class="rating">I cook at home sometimes.</h2><br/>
						<input type="radio" ng-model="newProfile.cooks" name="cooks" value="1">
					<h2 class="rating">I do not cook at all.</h2><br/>
	
				<label for="pets" class="questions">
					<h1 class="topic">Pets:</h1> </label><br>
						<input type="radio" ng-model="newProfile.pets" name="pets" value="1">
					<h2 class="rating">Yes.</h2><br/>
						<input type="radio" ng-model="newProfile.pets" name="pets" value="0">
					<h2 class="rating">No.</h2><br/>
					
				<label for="smoking" class="questions"> 
					<h1 class="topic">  Smoking:</h1><br> </label>
					It is okay to smoke inside the house? <br>
						<input type="radio" ng-model="newProfile.smoking" name="smoking" value="1">
					<h2 class="rating">Yes.</h2><br/>
						<input type="radio" ng-model="newProfile.smoking" name="smoking" value="0">
					<h2 class="rating">No.</h2><br/>
			
				<label for="interests"  class="questions">
					<h1 class="topic">  Interests:</h1></label>
						<textarea name="interests" ng-model="newProfile.interests" class="form-control" required></textarea><br><br>
				
				<label for="notes"  class="questions">
					<h1 class="topic">  Notes:</h1> </label>
						<textarea name="notes" ng-model="newProfile.notes" class="form-control" required></textarea><br><br>

				<input type="submit" value="Done!" class="linktosignup"><br><br>
						
				</form>
			</div>
		</div>


	<div class="small-6 large-2 columns" id="filtersidebar">
	
			<span class="mainfont">
				<%= current_user.name %><br>
				<%= current_user.age %>, <%= current_user.gender %><br>
				<%= current_user.city %>
			<div class="userpic">
				<%= image_tag current_user.avatar.url(:square) %><br><br>
			</div> <br><br><br>
			Edit Profile</span>
	</div>

</div>


		

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>


<div>
	<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
        <div id="error_explanation">

          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |user| %>
                <li><%= user %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
	<p>
	<%= f.text_field :email, :placeholder => "Email" %>
	<%= f.password_field :password, :placeholder => "Password" %><br><br>
	<%= f.text_field :name, :placeholder => "Name" %>
	<%= f.text_field :age, :placeholder => "Age" %><br><br>

	<%= f.select :gender, options_for_select(%w[Male Female LGBT]) %>

	<%= f.text_field :city, :placeholder => "City" %>
	<%= f.text_field :state, :placeholder => "State" %>

	</p>
	<%= f.label :avatar %>
	<%= f.file_field :avatar %>
	<%= button_to('Create Account', new_sessions_path, :class => 'btn btn-warning btn-mini')  %>
	<% end %>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>